name: "Python Poetry Login"
description: "A Github action that logs in to one or more Python repositories."
author: "Ali Samji <ali@ybor.ai>"

# Define the inputs for this action
inputs:
  upload-urls:
    description: "A registry=url mapping of registry aliases with their corresponding upload URLs. One per line."
    required: false
  credentials:
    description: "A registry=user:password mapping of registry aliases with their corresponding http-basic auth credentials. One per line."
    required: true

# Define the outputs for this action
# outputs: {}

# Define the runs configuration
runs:
  using: "composite"
  steps:
    - name: Configure Poetry repositories
      id: configure-repos
      shell: bash
      run: |
        # Configure upload URLs if provided
        if [ ! -z '${{ inputs.upload-urls }}' ]; then
          echo '${{ inputs.upload-urls }}' | while IFS='=' read -r registry url; do
            if [ ! -z "$registry" ] && [ ! -z "$url" ]; then
              poetry config repositories.$registry $url
            fi
          done
        fi

    - name: Configure Poetry credentials
      id: configure-auth
      shell: bash
      run: |
        # Configure authentication credentials
        echo '${{ inputs.credentials }}' | while IFS='=' read -r registry auth; do
          if [ ! -z "$registry" ] && [ ! -z "$auth" ]; then
            IFS=':' read -r username password <<< "$auth"
            poetry config http-basic.$registry "$username" "$password"
          fi
        done

# Define the branding for the action in the GitHub Marketplace
branding:
  icon: "award"
  color: "blue"
